config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'albums/new'
  end

  namespace :admin do
    get 'albums/edit'
  end

  root to: 'sessions#new'

  resources :albums, only: %i[index show]

  resources :songs, only: %i[index show]

  resources :users, exclude: %i[create] do
    resources :playlists
  end

  namespace :admin do
    resources :users, exclude: %i[show]
    resources :songs, exclude: %i[index show]
    resources :albums, exclude: %i[index show]
  end


  namespace :playlist do
    resources :songs, only: %i[create destroy]
  end

  get '/sign_up',   to: 'users#new'
  post '/sign_up',  to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  has_many :user_playlists
  has_many :playlists, through: :user_playlists
  enum role: %w[base admin]

  has_secure_password

  def options
    names = playlists.pluck(:name)
    ids = playlists.pluck(:id)
    names.zip(ids)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def edit
    render locals: { user: User.find(params[:id]) }
  end
  
  def update
    user = User.find(params[:id])
    if user.update(user_params)
      flash[:success] = 'User updated'
      redirect_to edit_admin_user_path(user)
    else
      flash.now[:danger] = "Invalid attributes"
      render :edit, locals: { user: user }
    end
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:success] = "#{user.username} has been created"
      redirect_to admin_users_path
    else
      flash.now[:danger] = "Invalid attributes"
      render :new
    end
  end

  def index
    render locals: { users: User.all }
  end

  def destroy
    User.destroy(params[:id])

    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :role)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    render file: '/public/404', status: 404 unless current_user.id == params[:id].to_i
  end

  def new
    render locals: { user: User.new }
  end

  def create
    if params[:user][:password] == params[:user][:confirm_password]
      user = User.new(user_params)
      if user.save
        log_in(user)
        redirect_to user_path(user.id)
      else
        flash.now[:danger] = 'Username already taken!'
        render 'new'
      end
    else
      flash.now[:danger] = 'Passwords do not match!'
      render 'new'
    end
  end

  def edit
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1 class="header page-header">Create Account</h1>
<%= form_for(:user, url: sign_up_path) do |f| %>

  <div class="form">
    <div class="form-area">
      <%= f.label :username, class: 'hidden' %>
      <%= f.text_field :username, placeholder: 'Username', class: 'form-info' %>
    </div>

    <div class="form-area">
      <%= f.label :password, class: 'hidden' %>
      <%= f.password_field :password, placeholder: 'Password', class: 'form-info' %>
    </div>

    <div class="form-area">
      <%= f.label :confirm_password, class: 'hidden' %>
      <%= f.password_field :confirm_password, placeholder: 'Confirm Password', class: 'form-info' %>
    </div>

    <div class="form-area">
      <%= f.submit 'Create Account', class: 'btn signup-btn' %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<h1 class="page-header header">
  <%= current_user.username %>'s Profile
</h1>

<div class="links">
  <%= link_to 'New Playlist', new_user_playlist_path(current_user), class: 'nav' %>
  <%= link_to 'My Playlists', "#{current_user.id}/playlists", class: 'nav' %>
  <%= link_to 'Manage Users', admin_users_path, class: 'nav' if current_admin %>
  <%= link_to 'Logout', logout_path, method: :delete, class: 'nav' %>
</div>