config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'albums/new'
  end

  namespace :admin do
    get 'albums/edit'
  end

  root to: 'sessions#new'

  resources :albums, only: %i[index show]

  resources :songs, only: %i[index show]

  resources :users, exclude: %i[create] do
    resources :playlists
  end

  namespace :admin do
    resources :users, exclude: %i[show]
    resources :songs, exclude: %i[index show]
    resources :albums, exclude: %i[index show]
  end


  namespace :playlist do
    resources :songs, only: %i[create destroy]
  end

  get '/sign_up',   to: 'users#new'
  post '/sign_up',  to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/song.rb
class Song < ApplicationRecord
  validates :name, presence: true
  belongs_to :album
  has_many :playlist_songs
  has_many :playlists, through: :playlist_songs
end

app/controllers/admin/songs_controller.rb
class Admin::SongsController < Admin::BaseController

  def edit
    render locals: { song: Song.find(params[:id]),
                     album_options: Album.options }
  end

  def update
    song = Song.find(params[:id])
    if song.update(song_params)
      flash[:success] = 'Song updated'
      redirect_to edit_admin_song_path(song)
    else
      flash.now[:danger] = 'Invalid attributes'
      redirect_to edit_admin_song_path(song)
    end
  end

  def new
    render locals: { album_options: Album.options }
  end

  def create
    song = Song.new(song_params)
    if song.save
      flash[:success] = 'Song successfully created.'

      redirect_to song_path(song)
    else
      flash.now[:danger] = 'Invalid input. Try again'
      render 'new', locals: { album_options: Album.options }
    end
  end

  def destroy
    Song.delete(params[:id])

    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:name, :album_id)
  end
end

app/controllers/playlist/songs_controller.rb
class Playlist::SongsController < ApplicationController

  def create
    playlist = Playlist.find(params[:playlist][:id])
    playlist.add_song(params[:playlist][:song_id])

    redirect_back(fallback_location: { controller: 'song', action: 'show' })
  end

  def destroy
    playlist = Playlist.find(params[:playlist])
    playlist.remove_song(params[:id])

    redirect_back(fallback_location: { controller: 'playlist', action: 'show' })
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    playlist_options = current_user.options if current_user

    render locals: { songs: Song.all, playlist_options: playlist_options }
  end

  def show
    playlist_options = current_user.options if current_user

    render locals: { song: Song.find(params[:id]), playlist_options: playlist_options }
  end
end

app/views/songs/_plist_form.html.erb
<div class="plist-add-form">
  <%= form_for(:playlist, url: playlist_songs_path, method: :post) do |f| %>
    <%= f.select(:id, options_for_select(options), class: 'playlist-dropdown') %>
    <%= f.label :song_id %>
    <%= f.text_field :song_id, value: song.id, class: 'hidden' %>
    <%= f.submit 'Add to Playlist', class: 'add-to-playlist-button btn' %>
  <% end %>
</div>

app/views/songs/index.html.erb
<h1 class="header page-header">
  Songs
</h1>

<div class="links">
  <%= link_to 'Create Song', new_admin_song_path, class: 'admin-create' if current_admin %>
  <% songs.each do |song| %>
    <%= link_to song.name, song_path(song), class: 'nav song' %>
    <%= link_to 'Edit', edit_admin_song_path(song), class: 'nav admin-links' if current_admin %>
  <% end %>
</div>

app/views/songs/show.html.erb
<h1 class="page-header header">
  <%= song.name %>
</h1>


<div class="plist-links">

  <%= link_to song.album.name, album_path(song.album), class: 'nav' %>

  <% if current_user %>
    <%= render partial: 'plist_form', locals: { song: song, options: playlist_options } %>
  <% end %>

</div>