config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'albums/new'
  end

  namespace :admin do
    get 'albums/edit'
  end

  root to: 'sessions#new'

  resources :albums, only: %i[index show]

  resources :songs, only: %i[index show]

  resources :users, exclude: %i[create] do
    resources :playlists
  end

  namespace :admin do
    resources :users, exclude: %i[show]
    resources :songs, exclude: %i[index show]
    resources :albums, exclude: %i[index show]
  end


  namespace :playlist do
    resources :songs, only: %i[create destroy]
  end

  get '/sign_up',   to: 'users#new'
  post '/sign_up',  to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/album.rb
class Album < ApplicationRecord
  validates :name, presence: true
  has_many :songs

  def self.options
    names = Album.pluck(:name)
    ids = Album.pluck(:id)
    names.zip(ids)
  end
end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < Admin::BaseController

  def new
  end

  def create
    album = Album.new(album_params)
    if album.save
      flash[:success] = 'Album saved.'
      redirect_to albums_path
    else
      flash.now[:danger] = 'Invalid info'
      render 'new'
    end
  end

  def edit
    render locals: { album: Album.find(params[:id]) }
  end

  def update
    album = Album.find(params[:id])
    if album.update(album_params)
      redirect_to edit_admin_album_path(album)
      flash[:success] = 'Successfully Updated'
    else
      render 'edit'
      flash.now[:danger] = 'Invalid attributes'
    end
  end

  def destroy
    Album.destroy(params[:id])

    redirect_to albums_path
  end

  private

  def album_params
    params.require(:album).permit(:name)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    render locals: { albums: Album.all }
  end

  def show
    render locals: { album: Album.find(params[:id]) }
  end
end

app/views/albums/index.html.erb
<h1 class="header page-header">
  Albums
</h1>

<div class="admin-header">
  <%= link_to 'Create Album', new_admin_album_path, class: 'admin-create' if current_admin %>
</div>
<% albums.each do |album| %>
  <div class="album">
    <%= image_tag('/assets/default_album.jpg', class: 'album-image') %>
    <%= link_to album.name, album_path(album), class: 'album-info' %>
    <%= link_to 'Edit', edit_admin_album_path(album), class: 'nav admin-links' if current_admin %>
  </div>
<% end %>

app/views/albums/show.html.erb
<h1 class="page-header header">
  <%= album.name %>
</h1>

<div class="album-show">
  <%= image_tag('/assets/default_album.jpg', class: 'album-image') %>
</div>

<h1 class="header">
  Tracks
</h3>

<% album.songs.each do |song| %>
  <div class="links">
    <%= link_to song.name, song_path(song), class: 'nav' %>
  </div>
<% end %>