config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'albums/new'
  end

  namespace :admin do
    get 'albums/edit'
  end

  root to: 'sessions#new'

  resources :albums, only: %i[index show]

  resources :songs, only: %i[index show]

  resources :users, exclude: %i[create] do
    resources :playlists
  end

  namespace :admin do
    resources :users, exclude: %i[show]
    resources :songs, exclude: %i[index show]
    resources :albums, exclude: %i[index show]
  end


  namespace :playlist do
    resources :songs, only: %i[create destroy]
  end

  get '/sign_up',   to: 'users#new'
  post '/sign_up',  to: 'users#create'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SpottyRailsMini</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css" rel="stylesheet">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js"> </script>
  </head>

  <body class="body">

  <header class="navbar-nav">

    <% unless current_user.nil? %>
      <%= link_to 'Albums', albums_path, class: 'navbar-link' %>
      <%= link_to 'Songs', songs_path, class: 'navbar-link' %>
      <%= link_to 'Users', admin_users_path, class: 'navbar-link' if current_admin %>
      <%= link_to current_user.username, user_path(current_user), class: 'navbar-link'  %>
    <% end %>

    <% if current_user.nil? %>
      <%= link_to 'Sign In', login_path, class: 'navbar-link' %>
      <%= link_to 'Sign Up', sign_up_path, class: 'navbar-link' %>
    <% end %>

  </header>

  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
  </body>
</html>